from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MplWidget
from ApplicationManager import *


class Ui_VoiceRecognizer(object):
    def setupUi(self, VoiceRecognizer):
        VoiceRecognizer.setObjectName("VoiceRecognizer")
        VoiceRecognizer.resize(1203, 772)
        VoiceRecognizer.setStyleSheet("background-color: #1e1e2f;")
        self.centralwidget = QtWidgets.QWidget(VoiceRecognizer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Public_RadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.Public_RadioButton.setChecked(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Public_RadioButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/Fingerprint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Public_RadioButton.setIcon(icon)
        self.Public_RadioButton.setIconSize(QtCore.QSize(50, 50))
        self.Public_RadioButton.setObjectName("Public_RadioButton")
        self.gridLayout_8.addWidget(self.Public_RadioButton, 0, 0, 1, 1)
        self.Private_RadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.Private_RadioButton.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Private_RadioButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/Unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Private_RadioButton.setIcon(icon1)
        self.Private_RadioButton.setIconSize(QtCore.QSize(40, 40))
        self.Private_RadioButton.setAutoRepeat(False)
        self.Private_RadioButton.setObjectName("radioButton")
        self.gridLayout_8.addWidget(self.Private_RadioButton, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.SpectrogramWidget = MplWidget(self.frame_3)
        self.SpectrogramWidget.setMinimumSize(QtCore.QSize(571, 0))
        self.SpectrogramWidget.setObjectName("SpectrogramWidget")
        self.gridLayout_4.addWidget(self.SpectrogramWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AccessLabel = QtWidgets.QLabel(self.frame_2)
        self.AccessLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.AccessLabel.setText("")
        self.AccessLabel.setObjectName("AccessLabel")
        self.gridLayout_3.addWidget(self.AccessLabel, 1, 2, 2, 1)
        self.VoiceRecognizedLabel = QtWidgets.QLabel(self.frame_2)
        self.VoiceRecognizedLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.VoiceRecognizedLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.VoiceRecognizedLabel.setObjectName("VoiceRecognizedLabel")
        self.gridLayout_3.addWidget(self.VoiceRecognizedLabel, 1, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-weight: bold;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.RecordButton = QtWidgets.QPushButton(self.frame_2, clicked = lambda: MAESTRO.record_voice())
        self.RecordButton.setMaximumSize(QtCore.QSize(75, 75))
        self.RecordButton.setStyleSheet("background-color: rgb(23, 142, 233);\n"
"border-radius: 25px;\n"
"")
        self.RecordButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/Microphone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecordButton.setIcon(icon2)
        self.RecordButton.setIconSize(QtCore.QSize(80, 80))
        self.RecordButton.setObjectName("RecordButton")
        self.gridLayout_3.addWidget(self.RecordButton, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 1, 1, 1)
        self.Hazem_Bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.Hazem_Bar.setProperty("value", 0)
        self.Hazem_Bar.setObjectName("Hazem_Bar")
        self.gridLayout_10.addWidget(self.Hazem_Bar, 1, 0, 1, 1)
        self.progressBar_8 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_8.setProperty("value", 0)
        self.progressBar_8.setObjectName("progressBar_8")
        self.gridLayout_10.addWidget(self.progressBar_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 2, 1, 1, 1)
        self.Omar_Bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.Omar_Bar.setProperty("value", 0)
        self.Omar_Bar.setObjectName("Omar_Bar")
        self.gridLayout_10.addWidget(self.Omar_Bar, 3, 0, 1, 1)
        self.progressBar_9 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_9.setProperty("value", 0)
        self.progressBar_9.setObjectName("progressBar_9")
        self.gridLayout_10.addWidget(self.progressBar_9, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 4, 1, 1, 1)
        self.Taha_Bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.Taha_Bar.setProperty("value", 0)
        self.Taha_Bar.setObjectName("Taha_Bar")
        self.gridLayout_10.addWidget(self.Taha_Bar, 5, 0, 1, 1)
        self.progressBar_10 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_10.setProperty("value", 0)
        self.progressBar_10.setObjectName("progressBar_10")
        self.gridLayout_10.addWidget(self.progressBar_10, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 6, 1, 1, 1)
        self.Youssef_Bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.Youssef_Bar.setProperty("value", 0)
        self.Youssef_Bar.setObjectName("Youssef_Bar")
        self.gridLayout_10.addWidget(self.Youssef_Bar, 7, 0, 1, 1)
        self.progressBar_11 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_11.setProperty("value", 0)
        self.progressBar_11.setObjectName("progressBar_11")
        self.gridLayout_10.addWidget(self.progressBar_11, 7, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_6, 2, 1, 2, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.Access_progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.Access_progressBar.setProperty("value", 0)
        self.Access_progressBar.setObjectName("Access_progressBar")
        self.gridLayout_9.addWidget(self.Access_progressBar, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 2, 0, 1, 1)
        self.Door_progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.Door_progressBar.setProperty("value", 0)
        self.Door_progressBar.setObjectName("Door_progressBar")
        self.gridLayout_9.addWidget(self.Door_progressBar, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 4, 0, 1, 1)
        self.Key_progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.Key_progressBar.setProperty("value", 0)
        self.Key_progressBar.setObjectName("Key_progressBar")
        self.gridLayout_9.addWidget(self.Key_progressBar, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 0, 1, 2, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        VoiceRecognizer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VoiceRecognizer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 26))
        self.menubar.setObjectName("menubar")
        VoiceRecognizer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VoiceRecognizer)
        self.statusbar.setObjectName("statusbar")
        VoiceRecognizer.setStatusBar(self.statusbar)

        self.retranslateUi(VoiceRecognizer)
        QtCore.QMetaObject.connectSlotsByName(VoiceRecognizer)

        self.Public_RadioButton.clicked.connect(lambda: MAESTRO.switch_modes())
        self.Private_RadioButton.clicked.connect(lambda: MAESTRO.switch_modes())


    def retranslateUi(self, VoiceRecognizer):
        _translate = QtCore.QCoreApplication.translate
        VoiceRecognizer.setWindowTitle(_translate("VoiceRecognizer", "MainWindow"))
        self.groupBox.setTitle(_translate("VoiceRecognizer", "Security Level"))
        self.Public_RadioButton.setText(_translate("VoiceRecognizer", "Security voice fingerprint"))
        self.Private_RadioButton.setText(_translate("VoiceRecognizer", "Security voice code"))
        self.label_4.setText(_translate("VoiceRecognizer", "Spectrogram"))
        self.VoiceRecognizedLabel.setText(_translate("VoiceRecognizer", "Press the recorder icon to start recording"))
        self.label_2.setText(_translate("VoiceRecognizer", "Voice Recognized"))
        self.label_6.setText(_translate("VoiceRecognizer", "Access"))
        self.groupBox_3.setTitle(_translate("VoiceRecognizer", "Persons Matching"))
        self.label_10.setText(_translate("VoiceRecognizer", "Hazem"))
        self.label_12.setText(_translate("VoiceRecognizer", "Person5"))
        self.label_9.setText(_translate("VoiceRecognizer", "Omar"))
        self.label_14.setText(_translate("VoiceRecognizer", "Person6"))
        self.label_8.setText(_translate("VoiceRecognizer", "Taha"))
        self.label_13.setText(_translate("VoiceRecognizer", "Person7"))
        self.label_11.setText(_translate("VoiceRecognizer", "Youssef"))
        self.label_15.setText(_translate("VoiceRecognizer", "Person8"))
        self.groupBox_2.setTitle(_translate("VoiceRecognizer", "Sentences Matching"))
        self.label.setText(_translate("VoiceRecognizer", "Grant Me Access"))
        self.label_3.setText(_translate("VoiceRecognizer", "Open Middle Door"))
        self.label_7.setText(_translate("VoiceRecognizer", "Release Entrance Key"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoiceRecognizer = QtWidgets.QMainWindow()
    ui = Ui_VoiceRecognizer()
    ui.setupUi(VoiceRecognizer)
    MAESTRO = ApplicationManger(ui)
    MAESTRO.create_database()
    VoiceRecognizer.show()
    sys.exit(app.exec_())
